# Generated by Django 5.2.7 on 2025-10-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('staff_lname', models.CharField(max_length=100)),
                ('staff_fname', models.CharField(max_length=100)),
                ('staff_mname', models.CharField(max_length=100, null=True)),
                ('staff_sex', models.CharField(max_length=50)),
                ('staff_dob', models.DateField()),
                ('staff_pos', models.CharField(max_length=50)),
                ('staff_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
    ]
