# Generated by Django 5.2.7 on 2025-10-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalemployee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_mname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
