# Generated by Django 5.2.7 on 2025-10-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('pat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pat_lname', models.CharField(max_length=100)),
                ('pat_fname', models.CharField(max_length=100)),
                ('pat_mname', models.CharField(max_length=100, null=True)),
                ('pat_sex', models.CharField(max_length=20)),
                ('pat_dob', models.DateField()),
                ('pat_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
