# Generated by Django 5.2.7 on 2025-11-08 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0003_alter_appointment_app_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('bill_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bill_status', models.CharField(default='Unpaid', max_length=50)),
                ('bill_amount', models.FloatField()),
                ('bill_created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
            ],
        ),
    ]
