# Generated by Django 5.2.7 on 2025-11-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billing',
            table='billing',
        ),
    ]
