# Generated by Django 5.2.7 on 2025-10-13 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicalemployee', '0002_alter_staff_staff_mname'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('app_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app_date', models.DateField()),
                ('app_start_time', models.TimeField()),
                ('app_end_time', models.TimeField()),
                ('app_room', models.TimeField()),
                ('app_status', models.CharField(max_length=50)),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalemployee.staff')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
