# Generated by Django 5.2.7 on 2025-11-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_app_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_status',
            field=models.CharField(default='SCHEDULED', max_length=50),
        ),
    ]
